In [5]:
# 打开文件夹
import numpy as np
import sys
test=np.genfromtxt('/Users/crq/PycharmProjects/learnPython/testnumpy/data.txt',delimiter=',',dtype=int)
print(type(test))

<class 'numpy.ndarray'>


In [6]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings in Python 3k.  The strings
   

## shape 用于查看numpy 数组的结构  用得很多

In [8]:
import numpy as np
n1=np.array([1,2,3,4])
n1.shape

(4,)

## dtype 查看具体的数据类型

In [10]:
n1.dtype

dtype('int64')

## numpy 不像list 等 其中的数据类型都必须是一样的

In [12]:
number1=np.array([1,2,3,4])
print(number1.dtype)
number1=np.array([1,2,3,4.0])
print(number1)
print(number1.dtype)

int64
[1. 2. 3. 4.]
float64


In [13]:
number=np.array([
    [1,2,3,4],
    [5,6,7,8]
])
number.shape

(2, 4)

In [15]:
number[:,1:2]  # 取得第1到2 列的所有行 因为是前闭后开 所以取得的是第一列

array([[2],
       [6]])

In [17]:
number[:,1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [18]:
number==4  # 对number 矩阵中的每一个元素都做了判断  返回bool类型

array([[False, False, False,  True],
       [False, False, False, False]])

In [19]:
# 使用
equal_to_four=(number==4)
#可以将该值当做一个索引 去矩阵中做一些操作

print(equal_to_four)
print(number[equal_to_four])

[[False False False  True]
 [False False False False]]
[4]


In [22]:
# 对其中元素做一个值类型的转换

number=np.array(['1','2','3'])
number=number.astype(float)
print(number.dtype)
print(number)

float64
[1. 2. 3.]


In [23]:
# 求极值操作

print(number.mean()) # 均值
print(number.min())

2.0
1.0


In [24]:
# 按行求和或 按列求和  指定维度 axis axis=0 列
matrix=np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
matrix.sum(axis=1) # 按行加

array([ 30,  75, 120])

In [26]:
m1=np.arange(1,10,2)  # 1到10  以2 为步长
m1

array([1, 3, 5, 7, 9])

In [27]:
m1.ndim  # 数组维度

1

In [29]:
np.linspace(0,1000,100) # 以0 为起点  2*pi 为终点 取100个


array([   0.        ,   10.1010101 ,   20.2020202 ,   30.3030303 ,
         40.4040404 ,   50.50505051,   60.60606061,   70.70707071,
         80.80808081,   90.90909091,  101.01010101,  111.11111111,
        121.21212121,  131.31313131,  141.41414141,  151.51515152,
        161.61616162,  171.71717172,  181.81818182,  191.91919192,
        202.02020202,  212.12121212,  222.22222222,  232.32323232,
        242.42424242,  252.52525253,  262.62626263,  272.72727273,
        282.82828283,  292.92929293,  303.03030303,  313.13131313,
        323.23232323,  333.33333333,  343.43434343,  353.53535354,
        363.63636364,  373.73737374,  383.83838384,  393.93939394,
        404.04040404,  414.14141414,  424.24242424,  434.34343434,
        444.44444444,  454.54545455,  464.64646465,  474.74747475,
        484.84848485,  494.94949495,  505.05050505,  515.15151515,
        525.25252525,  535.35353535,  545.45454545,  555.55555556,
        565.65656566,  575.75757576,  585.85858586,  595.95959

使用tile扩展数组 横向 纵向扩展

括号中的3,5 代表行变成3 倍 列变成5倍

In [33]:
a=np.arange(0,40,10)
print(a)
b=np.tile(a,(3,5))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


排序
sort为排序函数 axis=1  表示按横轴进行排序
argsort 求值得索引

可以得出数值大小的索引 比如说 4，3，1，2 的索引就是2，3，1，0(1在index=2 的位置上  以此类推)

In [35]:
a=np.array([
    [4,3,5],
    [1,2,1]
])
print(a)
print('-----------')
b=np.sort(a,axis=1)
print(b)

a=np.array([4,3,1,2])
j=np.argsort(a)
print('-------')
print(j)
print('---------')
print(a[j])

[[4 3 5]
 [1 2 1]]
-----------
[[3 4 5]
 [1 1 2]]
-------
[2 3 1 0]
---------
[1 2 3 4]
